branches:
  except:
    - gh-pages
language: perl6
sudo: required
perl6:
  - latest
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y libnotmuch-dev
install:
  - rakudobrew build-panda
  - export PATH=~/.rakudobrew/bin:~/.rakudobrew/moar-nom/install/share/perl6/site/bin:~/.rakudobrew/moar-nom/panda/bin:$PATH
  - panda installdeps .
